using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;
using TrainingManagement.Application.Attempts;
using TrainingManagement.Application.Enrollments;
using TrainingManagement.Application.Progress;
using TrainingManagement.Domain.Constants;
using TrainingManagement.Domain.Entities;
using TrainingManagement.Domain.Enums;
using TrainingManagement.Infrastructure.Identity;
using TrainingManagement.Infrastructure.Persistence;
using TrainingManagement.Infrastructure.Services;
using AdminEnrollmentsController=TrainingManagement.Web.Areas.Admin.Controllers.EnrollmentsController;
using LearnerAttemptsController=TrainingManagement.Web.Areas.Learner.Controllers.AttemptsController;
using TrainerProgressController=TrainingManagement.Web.Areas.Trainer.Controllers.LearnerProgressController;

namespace TrainingManagement.Tests;

public sealed class EnrollmentsAttemptsProgressTests
{
    [Fact]public async Task NonLearner_CannotEnroll(){await using var p=Provider();using var s=p.CreateScope();await Roles(s);var u=await User(s,"admin@test",AppRoles.Admin);var c=await Course(s,true);Assert.False((await E(s).EnrollFreeAsync(c.Training.Id,u.Id)).Succeeded);}
    [Fact]public async Task ArchivedTraining_RejectsEnrollment(){await using var p=Provider();using var s=p.CreateScope();await Roles(s);var u=await User(s,"l@test",AppRoles.Learner);var c=await Course(s,true,true);Assert.False((await E(s).CreateByAdminAsync(new(u.Id,c.Training.Id,true,"admin"))).Succeeded);}
    [Fact]public async Task FreeTraining_AllowsDirectEnrollment(){await using var p=Provider();using var s=p.CreateScope();await Roles(s);var u=await User(s,"l@test",AppRoles.Learner);var c=await Course(s,true);Assert.True((await E(s).EnrollFreeAsync(c.Training.Id,u.Id)).Succeeded);}
    [Fact]public async Task PaidTraining_RejectsDirectEnrollment(){await using var p=Provider();using var s=p.CreateScope();await Roles(s);var u=await User(s,"l@test",AppRoles.Learner);var c=await Course(s,false);Assert.False((await E(s).EnrollFreeAsync(c.Training.Id,u.Id)).Succeeded);}
    [Fact]public async Task ActiveDuplicate_IsRejected(){await using var p=Provider();using var s=p.CreateScope();await Roles(s);var u=await User(s,"l@test",AppRoles.Learner);var c=await Course(s,true);await E(s).EnrollFreeAsync(c.Training.Id,u.Id);Assert.False((await E(s).EnrollFreeAsync(c.Training.Id,u.Id)).Succeeded);}
    [Fact]public async Task ActiveEnrollment_AllowsAccess(){await using var p=Provider();using var s=p.CreateScope();var c=await Course(s);var e=await Enrollment(s,c,"x",EnrollmentStatus.Active);Assert.True(await E(s).CanAccessTrainingAsync(c.Training.Id,e.LearnerId));}
    [Fact]public async Task PendingEnrollment_DeniesAccess(){await using var p=Provider();using var s=p.CreateScope();var c=await Course(s);var e=await Enrollment(s,c,"x",EnrollmentStatus.Pending);Assert.False(await E(s).CanAccessTrainingAsync(c.Training.Id,e.LearnerId));}
    [Fact]public async Task SuspendedEnrollment_DeniesAccess(){await using var p=Provider();using var s=p.CreateScope();var c=await Course(s);var e=await Enrollment(s,c,"x",EnrollmentStatus.Suspended);Assert.False(await E(s).CanAccessTrainingAsync(c.Training.Id,e.LearnerId));}
    [Fact]public async Task CompletedEnrollment_KeepsAccess(){await using var p=Provider();using var s=p.CreateScope();var c=await Course(s);var e=await Enrollment(s,c,"x",EnrollmentStatus.Completed);Assert.True(await E(s).CanAccessTrainingAsync(c.Training.Id,e.LearnerId));}
    [Fact]public async Task Admin_CanActivateEnrollment(){await using var p=Provider();using var s=p.CreateScope();var c=await Course(s);var e=await Enrollment(s,c,"x",EnrollmentStatus.Pending);Assert.True((await E(s).ActivateAsync(e.Id)).Succeeded);Assert.Equal(EnrollmentStatus.Active,(await Db(s).Enrollments.FindAsync(e.Id))!.Status);}

    [Fact]public async Task FirstAccess_CreatesProgress(){await using var p=Provider();using var s=p.CreateScope();var setup=await Ready(s);var r=await P(s).RecordAccessAsync(setup.Course.Lesson.Id,setup.UserId);Assert.True(r.Succeeded);Assert.Single(Db(s).LessonProgresses);}
    [Fact]public async Task FirstAccessAt_IsNotOverwritten(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var first=await P(s).RecordAccessAsync(x.Course.Lesson.Id,x.UserId);var time=first.Value!.FirstAccessedAt;await Task.Delay(5);var second=await P(s).RecordAccessAsync(x.Course.Lesson.Id,x.UserId);Assert.Equal(time,second.Value!.FirstAccessedAt);}
    [Fact]public async Task LastAccessAt_IsUpdated(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var first=await P(s).RecordAccessAsync(x.Course.Lesson.Id,x.UserId);await Task.Delay(5);var second=await P(s).RecordAccessAsync(x.Course.Lesson.Id,x.UserId);Assert.True(second.Value!.LastAccessedAt>first.Value!.LastAccessedAt);}
    [Fact]public async Task Lesson_CanBeCompleted(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var r=await P(s).CompleteAsync(x.Course.Lesson.Id,x.UserId);Assert.True(r.Succeeded);Assert.Equal(LessonProgressStatus.Completed,(await Db(s).LessonProgresses.SingleAsync()).Status);}
    [Fact]public async Task OnlyOneProgress_PerEnrollmentLesson(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);await P(s).RecordAccessAsync(x.Course.Lesson.Id,x.UserId);await P(s).RecordAccessAsync(x.Course.Lesson.Id,x.UserId);Assert.Single(Db(s).LessonProgresses);}
    [Fact]public async Task LessonFromOtherTraining_IsRejected(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var other=await Course(s);Assert.False((await P(s).RecordAccessAsync(other.Lesson.Id,x.UserId)).Succeeded);}
    [Fact]public async Task ArchivedLessons_AreExcludedFromProgress(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);x.Course.SecondLesson.IsArchived=true;await Db(s).SaveChangesAsync();var r=await P(s).CompleteAsync(x.Course.Lesson.Id,x.UserId);Assert.Equal(100,r.Value!.ProgressPercentage);}
    [Fact]public async Task Progress_IsCalculatedCorrectly(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var r=await P(s).CompleteAsync(x.Course.Lesson.Id,x.UserId);Assert.Equal(50,r.Value!.ProgressPercentage);}
    [Fact]public async Task Enrollment_CompletesAtHundredPercent(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);await P(s).CompleteAsync(x.Course.Lesson.Id,x.UserId);var r=await P(s).CompleteAsync(x.Course.SecondLesson.Id,x.UserId);Assert.Equal(EnrollmentStatus.Completed,r.Value!.EnrollmentStatus);}

    [Fact]public async Task Attempt_RequiresEnrollment(){await using var p=Provider();using var s=p.CreateScope();var c=await Course(s);Assert.False((await A(s).StartAsync(new(c.Assessment.Id,"none"))).Succeeded);}
    [Fact]public async Task AssessmentFromOtherTraining_IsRejected(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var other=await Course(s);Assert.False((await A(s).StartAsync(new(other.Assessment.Id,x.UserId))).Succeeded);}
    [Fact]public async Task AttemptNumber_StartsAtOne(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var r=await A(s).StartAsync(new(x.Course.Assessment.Id,x.UserId));Assert.Equal(1,(await Db(s).AssessmentAttempts.FindAsync(r.Value))!.AttemptNumber);}
    [Fact]public async Task AttemptNumber_Increments(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var first=await Start(s,x);await A(s).SubmitAsync(new(first,x.UserId,[]));var second=await A(s).StartAsync(new(x.Course.Assessment.Id,x.UserId));Assert.Equal(2,(await Db(s).AssessmentAttempts.FindAsync(second.Value))!.AttemptNumber);}
    [Fact]public async Task OnlyOneInProgressAttempt_IsReturned(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var a=await A(s).StartAsync(new(x.Course.Assessment.Id,x.UserId));var b=await A(s).StartAsync(new(x.Course.Assessment.Id,x.UserId));Assert.Equal(a.Value,b.Value);}
    [Fact]public async Task MaximumAttempts_IsRespected(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s,maxAttempts:1);var id=await Start(s,x);await A(s).SubmitAsync(new(id,x.UserId,[]));Assert.False((await A(s).StartAsync(new(x.Course.Assessment.Id,x.UserId))).Succeeded);}
    [Fact]public async Task ExpiresAt_IsCalculated(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s,time:10);var id=await Start(s,x);var a=await Db(s).AssessmentAttempts.FindAsync(id);Assert.InRange((a!.ExpiresAt-a.StartedAt)!.Value.TotalMinutes,9.9,10.1);}
    [Fact]public async Task ExpiredAttempt_CannotBeModified(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var id=await Start(s,x);var a=await Db(s).AssessmentAttempts.FindAsync(id);a!.ExpiresAt=DateTime.UtcNow.AddSeconds(-1);await Db(s).SaveChangesAsync();Assert.False((await A(s).SaveAnswersAsync(id,x.UserId,[])).Succeeded);}
    [Fact]public async Task SubmittedAttempt_CannotBeModified(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var id=await Start(s,x);await A(s).SubmitAsync(new(id,x.UserId,[]));Assert.False((await A(s).SaveAnswersAsync(id,x.UserId,[])).Succeeded);}
    [Fact]public async Task MaximumScore_IsCalculated(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var id=await Start(s,x);Assert.Equal(5,(await Db(s).AssessmentAttempts.FindAsync(id))!.MaximumScore);}
    [Fact]public async Task AttemptSnapshots_AreCreated(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var id=await Start(s,x);var snapshots=await Db(s).AttemptQuestions.Where(q=>q.AssessmentAttemptId==id).ToListAsync();Assert.Equal(4,snapshots.Count);Assert.All(snapshots,q=>Assert.NotEmpty(q.StatementSnapshot));}
    [Fact]public async Task ShuffledOrder_RemainsStable(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s,shuffle:true);var id=await Start(s,x);var one=(await A(s).GetAttemptAsync(id,x.UserId))!.Questions.Select(q=>q.AttemptQuestionId);var two=(await A(s).GetAttemptAsync(id,x.UserId))!.Questions.Select(q=>q.AttemptQuestionId);Assert.Equal(one,two);}
    [Fact]public async Task DoubleSubmission_IsRejected(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var id=await Start(s,x);Assert.True((await A(s).SubmitAsync(new(id,x.UserId,[]))).Succeeded);Assert.False((await A(s).SubmitAsync(new(id,x.UserId,[]))).Succeeded);}

    [Fact]public void SingleChoiceCorrect_GivesAllPoints(){Assert.Equal(2,Score(QuestionType.SingleChoice,"1",null,[1],2).Score);}
    [Fact]public void SingleChoiceIncorrect_GivesZero(){Assert.Equal(0,Score(QuestionType.SingleChoice,"1",null,[2],2).Score);}
    [Fact]public void MultipleChoiceExact_GivesAllPoints(){Assert.Equal(3,Score(QuestionType.MultipleChoice,"1,2",null,[1,2],3).Score);}
    [Fact]public void MultipleChoiceIncomplete_GivesZero(){Assert.Equal(0,Score(QuestionType.MultipleChoice,"1,2",null,[1],3).Score);}
    [Fact]public void MultipleChoiceWithWrongChoice_GivesZero(){Assert.Equal(0,Score(QuestionType.MultipleChoice,"1,2",null,[1,2,3],3).Score);}
    [Fact]public void TrueFalse_IsScored(){Assert.True(Score(QuestionType.TrueFalse,"10",null,[10],1).Passed);}
    [Fact]public void ShortAnswer_IgnoresCase(){Assert.Equal(1,Score(QuestionType.ShortAnswer,null,"Program.cs",[],1,"program.CS").Score);}
    [Fact]public void ShortAnswer_TrimsSpaces(){Assert.Equal(1,Score(QuestionType.ShortAnswer,null,"Program.cs",[],1,"  Program.cs  ").Score);}
    [Fact]public void TotalScore_IsCalculated(){var svc=new AttemptScoringService();var r=svc.Score([new(1,QuestionType.SingleChoice,2,"1",null,[1],null),new(2,QuestionType.ShortAnswer,3,null,"x",[],"x")],50);Assert.Equal(5,r.Score);}
    [Fact]public void Percentage_IsCalculated(){var r=Score(QuestionType.SingleChoice,"1",null,[1],2);Assert.Equal(100,r.PercentageScore);}
    [Fact]public void Passed_UsesPassingScore(){var svc=new AttemptScoringService();var r=svc.Score([new(1,QuestionType.SingleChoice,1,"1",null,[2],null)],70);Assert.False(r.Passed);}

    [Fact]public async Task Learner_CannotSeeOtherAttempt(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var id=await Start(s,x);Assert.Null(await A(s).GetAttemptAsync(id,"other"));}
    [Fact]public async Task Trainer_CannotSeeUnassignedResult(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s,trainerId:"owner");var id=await Start(s,x);await A(s).SubmitAsync(new(id,x.UserId,[]));Assert.Null(await A(s).GetTrainerResultAsync(id,"other"));}
    [Fact]public async Task Trainer_CanSeeAssignedResult(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s,trainerId:"owner");var id=await Start(s,x);await A(s).SubmitAsync(new(id,x.UserId,[]));Assert.NotNull(await A(s).GetTrainerResultAsync(id,"owner"));}
    [Fact]public void LearnerRoutes_RequireLearnerRole(){Assert.Equal(AppRoles.Learner,Role<LearnerAttemptsController>());}
    [Fact]public async Task UnenrolledUser_CannotAccessPrivateLesson(){await using var p=Provider();using var s=p.CreateScope();var c=await Course(s);var pedagogy=new PedagogyReadService(Db(s));Assert.Null(await pedagogy.GetEnrolledLessonByIdAsync(c.Lesson.Id,"none"));}
    [Fact]public void AdminRoutes_RequireAdminRole(){Assert.Equal(AppRoles.Admin,Role<AdminEnrollmentsController>());}
    [Fact]public void TrainerRoutes_RequireTrainerRole(){Assert.Equal(AppRoles.Trainer,Role<TrainerProgressController>());}

    [Fact]public async Task CorrectAnswers_AreVisibleWhenEnabled(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s,showCorrect:true);var id=await Start(s,x);await SubmitCorrectSingle(s,x,id);var r=await A(s).GetResultAsync(id,x.UserId);Assert.Contains(r!.Questions,q=>q.CorrectAnswer is not null);}
    [Fact]public async Task CorrectAnswers_AreHiddenWhenDisabled(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s,showCorrect:false);var id=await Start(s,x);await SubmitCorrectSingle(s,x,id);var r=await A(s).GetResultAsync(id,x.UserId);Assert.All(r!.Questions,q=>Assert.Null(q.CorrectAnswer));}
    [Fact]public async Task ExpectedAnswer_IsHiddenWhenConfigured(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s,showCorrect:false);var id=await Start(s,x);await A(s).SubmitAsync(new(id,x.UserId,[]));var r=await A(s).GetResultAsync(id,x.UserId);Assert.DoesNotContain(r!.Questions,q=>q.CorrectAnswer=="Program.cs");}
    [Fact]public async Task ExpiredAttempt_HasExpiredStatus(){await using var p=Provider();using var s=p.CreateScope();var x=await Ready(s);var id=await Start(s,x);var a=await Db(s).AssessmentAttempts.FindAsync(id);a!.ExpiresAt=DateTime.UtcNow.AddSeconds(-1);await Db(s).SaveChangesAsync();await A(s).GetAttemptAsync(id,x.UserId);Assert.Equal(AttemptStatus.Expired,(await Db(s).AssessmentAttempts.FindAsync(id))!.Status);}

    [Fact]public async Task Seed_IsIdempotent(){await using var p=Provider(true);using var s=p.CreateScope();await Roles(s);var seed=s.ServiceProvider.GetRequiredService<DevelopmentDataSeeder>();await seed.SeedAsync();var first=(await Db(s).Enrollments.CountAsync(),await Db(s).LessonProgresses.CountAsync());Db(s).ChangeTracker.Clear();await seed.SeedAsync();Assert.Equal(first,(await Db(s).Enrollments.CountAsync(),await Db(s).LessonProgresses.CountAsync()));}
    [Fact]public async Task Seed_CreatesLearner(){await using var p=Provider(true);using var s=p.CreateScope();await Roles(s);await s.ServiceProvider.GetRequiredService<DevelopmentDataSeeder>().SeedAsync();Assert.NotNull(await Users(s).FindByEmailAsync("learner@training.local"));}
    [Fact]public async Task Seed_CreatesCoherentEnrollment(){await using var p=Provider(true);using var s=p.CreateScope();await Roles(s);await s.ServiceProvider.GetRequiredService<DevelopmentDataSeeder>().SeedAsync();var e=await Db(s).Enrollments.Include(x=>x.LessonProgresses).SingleAsync();Assert.Equal(EnrollmentStatus.Active,e.Status);Assert.InRange(e.ProgressPercentage,0.01m,99.99m);Assert.Contains(e.LessonProgresses,x=>x.Status==LessonProgressStatus.Completed);}

    private sealed record CourseData(Training Training,TrainingModule Module,Lesson Lesson,Lesson SecondLesson,Assessment Assessment,Question Single);
    private sealed record ReadyData(CourseData Course,string UserId,Enrollment Enrollment);
    private static ServiceProvider Provider(bool seed=false){var c=new ServiceCollection();c.AddLogging();c.AddDbContext<ApplicationDbContext>(o=>o.UseInMemoryDatabase(Guid.NewGuid().ToString()));c.AddIdentityCore<ApplicationUser>().AddRoles<IdentityRole>().AddEntityFrameworkStores<ApplicationDbContext>();c.AddScoped<IEnrollmentService,EnrollmentService>();c.AddScoped<ILessonProgressService,LessonProgressService>();c.AddSingleton<IAttemptScoringService,AttemptScoringService>();c.AddScoped<IAssessmentAttemptService,AssessmentAttemptService>();if(seed){c.AddSingleton<IOptions<SeedTrainerOptions>>(Options.Create(new SeedTrainerOptions{Email="trainer@training.local",Password="Trainer123!",FirstName="T",LastName="D"}));c.AddSingleton<IOptions<SeedLearnerOptions>>(Options.Create(new SeedLearnerOptions()));c.AddScoped<DevelopmentDataSeeder>();}return c.BuildServiceProvider();}
    private static ApplicationDbContext Db(IServiceScope s)=>s.ServiceProvider.GetRequiredService<ApplicationDbContext>();private static UserManager<ApplicationUser>Users(IServiceScope s)=>s.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();private static IEnrollmentService E(IServiceScope s)=>s.ServiceProvider.GetRequiredService<IEnrollmentService>();private static ILessonProgressService P(IServiceScope s)=>s.ServiceProvider.GetRequiredService<ILessonProgressService>();private static IAssessmentAttemptService A(IServiceScope s)=>s.ServiceProvider.GetRequiredService<IAssessmentAttemptService>();
    private static async Task Roles(IServiceScope s){var r=s.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();foreach(var role in AppRoles.All)if(!await r.RoleExistsAsync(role))await r.CreateAsync(new IdentityRole(role));}
    private static async Task<ApplicationUser>User(IServiceScope s,string email,string role){var u=new ApplicationUser{UserName=email,Email=email,FirstName="Test",LastName="User"};await Users(s).CreateAsync(u,"Password1!");await Users(s).AddToRoleAsync(u,role);return u;}
    private static async Task<CourseData>Course(IServiceScope s,bool free=true,bool archived=false,string? trainerId=null,bool showCorrect=true,int? maxAttempts=3,int? time=10,bool shuffle=false){var cat=new Category{Name="C"+Guid.NewGuid(),Slug="c-"+Guid.NewGuid()};var tr=new Training{Title="Course",Slug="course-"+Guid.NewGuid(),ShortDescription="Short",Description="D",Category=cat,Language="Français",EstimatedDurationHours=1,IsFree=free,Price=free?0:100,Status=archived?TrainingStatus.Archived:TrainingStatus.Published,TrainerId=trainerId};var m=new TrainingModule{Training=tr,Title="Module",Slug="module",Order=1,IsPublished=true};var l=new Lesson{TrainingModule=m,Title="Private",Slug="private",Order=1,IsPublished=true,IsPreview=false};var l2=new Lesson{TrainingModule=m,Title="Second",Slug="second",Order=2,IsPublished=true};var ass=new Assessment{Lesson=l,Title="Quiz",Slug="quiz",Order=1,PassingScore=70,MaximumAttempts=maxAttempts,TimeLimitMinutes=time,ShuffleQuestions=shuffle,ShowCorrectAnswers=showCorrect,IsPublished=true};var single=new Question{Assessment=ass,QuestionType=QuestionType.SingleChoice,Statement="Single",Order=1,Points=1,IsPublished=true};single.AnswerOptions.Add(new(){Text="A",Order=1,IsCorrect=true});single.AnswerOptions.Add(new(){Text="B",Order=2});var multi=new Question{Assessment=ass,QuestionType=QuestionType.MultipleChoice,Statement="Multi",Order=2,Points=2,IsPublished=true};multi.AnswerOptions.Add(new(){Text="A",Order=1,IsCorrect=true});multi.AnswerOptions.Add(new(){Text="B",Order=2,IsCorrect=true});multi.AnswerOptions.Add(new(){Text="C",Order=3});var tf=new Question{Assessment=ass,QuestionType=QuestionType.TrueFalse,Statement="TF",Order=3,Points=1,IsPublished=true};tf.AnswerOptions.Add(new(){Text="Vrai",Order=1,IsCorrect=true});tf.AnswerOptions.Add(new(){Text="Faux",Order=2});var shortQ=new Question{Assessment=ass,QuestionType=QuestionType.ShortAnswer,Statement="Short",ExpectedAnswer="Program.cs",Order=4,Points=1,IsPublished=true};Db(s).AddRange(l2,single,multi,tf,shortQ);await Db(s).SaveChangesAsync();return new(tr,m,l,l2,ass,single);}
    private static async Task<Enrollment>Enrollment(IServiceScope s,CourseData c,string learner,EnrollmentStatus status){var e=new Enrollment{TrainingId=c.Training.Id,LearnerId=learner,Status=status,EnrolledAt=DateTime.UtcNow};Db(s).Add(e);await Db(s).SaveChangesAsync();return e;}
    private static async Task<ReadyData>Ready(IServiceScope s,bool showCorrect=true,int? maxAttempts=3,int? time=10,bool shuffle=false,string? trainerId=null){var c=await Course(s,true,false,trainerId,showCorrect,maxAttempts,time,shuffle);var id="learner-"+Guid.NewGuid();var e=await Enrollment(s,c,id,EnrollmentStatus.Active);return new(c,id,e);}
    private static async Task<int>Start(IServiceScope s,ReadyData x)=>(await A(s).StartAsync(new(x.Course.Assessment.Id,x.UserId))).Value;
    private static ScoringResult Score(QuestionType type,string? correct,string? expected,IReadOnlyCollection<int> selected,decimal points,string? text=null)=>new AttemptScoringService().Score([new(1,type,points,correct,expected,selected,text)],50);
    private static string?Role<T>()=>typeof(T).GetCustomAttributes(typeof(AuthorizeAttribute),true).Cast<AuthorizeAttribute>().Single().Roles;
    private static async Task SubmitCorrectSingle(IServiceScope s,ReadyData x,int id){var detail=await A(s).GetAttemptAsync(id,x.UserId);var q=detail!.Questions.Single(q=>q.QuestionType==QuestionType.SingleChoice);var option=q.Options.Single(o=>o.Text=="A");await A(s).SubmitAsync(new(id,x.UserId,[new(q.AttemptQuestionId,[option.Id],null)]));}
}
